services:
  server:
    image: todo-backend-dev
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_started
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    environment: 
      REDIS_URL: redis://redis
      MONGO_URL: mongodb://the_username:the_password@mongo/the_database
    container_name: todo-backend-dev
  
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
  
  redis:
    image: redis
    ports:
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes'] 
    volumes: 
      - ./redis_data:/data